# Generated by Django 5.0.6 on 2024-05-26 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagem',
            name='introducao_1',
            field=models.TextField(default='introducao padrão'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imagem',
            name='introducao_2',
            field=models.TextField(default='introducao padrão 2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imagem',
            name='profissao',
            field=models.CharField(default='profissão do personagem', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imagem',
            name='text_final_1',
            field=models.TextField(default='final do artigo sobre'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imagem',
            name='text_final_2',
            field=models.TextField(default='final do artigo sobre'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imagem',
            name='text_habilidades',
            field=models.TextField(default='habilidades ou poderes do personagem'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imagem',
            name='text_profissao',
            field=models.TextField(default='sobre a profissão do personagem no anime'),
            preserve_default=False,
        ),
    ]
