# Generated by Django 5.0.6 on 2024-05-26 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0002_imagem_introducao_1_imagem_introducao_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagem',
            name='publicada',
            field=models.BooleanField(default=False),
        ),
    ]
