# Generated by Django 5.0.6 on 2024-05-26 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0003_imagem_publicada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagem',
            name='foto',
            field=models.ImageField(blank=True, upload_to='fotos/%Y/%m/%d/'),
        ),
    ]
